release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
- id: vault-plugin-auth-imap
  main: ./cmd/vault-plugin-auth-imap
  ldflags: >-
      -s -w
      -X "github.com/mabunixda/vault-plugin-auth-imap/version.Version={{ .Tag }}"
      -X "github.com/mabunixda/vault-plugin-auth-imap/version.BuildDate={{ .CommitDate }}"
      -X "github.com/mabunixda/vault-plugin-auth-imap/version.GoVersion={{ .Env.GOVERSION }}"
      -X "github.com/mabunixda/vault-plugin-auth-imap/version.GitCommit={{ .Env.GITHUB_SHA }}"
      -X "github.com/mabunixda/vault-plugin-auth-imap/version.GitDirty={{ .Env.GIT_DIRTY }}"
  env:
    - CGO_ENABLED=0
  goos:
#    - freebsd
    - windows
    - darwin
    - linux
#    - netbsd
#    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
#    - 386
  goarm:
    - 6
    - 7

archives:
  -
    id: vault-plugin-auth-imap
    builds:
    - vault-plugin-auth-imap
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
