version: 2
release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  - id: vault-plugin-auth-imap
    main: ./cmd/vault-plugin-auth-imap
    ldflags: "{{ .Env.LD_FLAGS }}"
    env:
      - CGO_ENABLED=0
    goos:
      #    - freebsd
      - windows
      - darwin
      - linux
    #    - netbsd
    #    - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    #    - 386
    goarm:
      - 6
      - 7

archives:
  - id: vault-plugin-auth-imap
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
    builds_info:
      group: root
      owner: root
      mode: 0644
      # format is `time.RFC3339Nano`
      mtime: 2008-01-02T15:04:05Z
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
