release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
- id: vault-plugin-auth-imap
  main: ./cmd/vault-plugin-auth-imap
  env:
    - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - darwin
    - linux
    - netbsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goarm:
    - 6
    - 7

archives:
  -
    id: vault-plugin-auth-imap
    builds:
    - vault-plugin-auth-imap
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
