---
name: Clean Go

env:
  GO_VERSION: ^1.24

permissions:
  contents: read # Read repository content and code
  pull-requests: read # Read PR information (if needed for context)
  checks: write # Write check results (for status checks)

on:
  push:
    branches: ["**", "!main"]

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
        id: go

      - name: Assets
        run: make assets

      - name: Porcelain
        run: make porcelain
